routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Sopamo\LaravelFilepond\Http\Controllers\FilepondController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resources([
    'employee' => App\Http\Controllers\EmployeeController::class,
    'company' => App\Http\Controllers\CompanyController::class,
]);

Route::prefix('api')->group(function () {
    Route::post('/process', [FilepondController::class, 'upload'])->name('pond.upload');
    Route::delete('/process', [FilepondController::class, 'delete'])->name('pond.delete');
});

Auth::routes(['register' => false]);

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Company
 *
 * @property $id
 * @property $name
 * @property $email
 * @property $email_verified_at
 * @property $logo_path
 * @property $website
 * @property $remember_token
 * @property $created_at
 * @property $updated_at
 *
 * @property Employee[] $employees
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Company extends Model
{

  protected $table = 'companies';


  static $rules = [
    'name' => 'required',
    'email' => 'required',
  ];

  protected $perPage = 20;

  /**
   * Attributes that should be mass-assignable.
   *
   * @var array
   */
  protected $fillable = ['name', 'email', 'logo_path', 'website'];

  public function getPhotoAttribute()
  {
    if (!empty($this->logo_path)) {
      return str_replace(env('ALT_STORE_PATH'), '', $this->logo_path);
    }

    return null; //or default image
  }

  /**
   * @return \Illuminate\Database\Eloquent\Relations\HasMany
   */
  public function employees()
  {
    return $this->hasMany('App\Models\Employee', 'companies_id', 'id');
  }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Models\Company;
use \App\Http\Requests\CompanyRequest;

/**
 * Class CompanyController
 * @package App\Http\Controllers
 */
class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Company::paginate(10);

        return view('company.index', compact('companies'))
            ->with('i', (request()->input('page', 1) - 1) * $companies->perPage());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $company = new Company();
        return view('company.create', compact('company'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\CompanyRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(CompanyRequest $request)
    {
        request()->validate(Company::$rules);
        $company = Company::create($request->all());

        if (!empty($input['file'])) {
            dd($input['file']);
            // Get the temporary path using the serverId returned by the upload function in `FilepondController.php`            
            $filepond = app(\Sopamo\LaravelFilepond\Filepond::class);
            $company->logo_path = $filepond->getPathFromServerId($input['file']);
            $company->save();
        }

        return redirect()->route('company.index')
            ->with('success', 'Company created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $company = Company::find($id);

        return view('company.show', compact('company'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = Company::find($id);

        return view('company.edit', compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\CompanyRequest $request
     * @param  Company $company
     * @return \Illuminate\Http\Response
     */
    public function update(CompanyRequest $request, Company $company)
    {
        request()->validate(Company::$rules);

        $company->update($request->all());

        $input = $request->input();

        if (!empty($input['file'][0])) {
            // Get the temporary path using the serverId returned by the upload function in `FilepondController.php`            
            $filepond = app(\Sopamo\LaravelFilepond\Filepond::class);
            $company->logo_path = $filepond->getPathFromServerId($input['file'][0]);
            $company->save();
        }

        return redirect()->route('company.index')
            ->with('success', 'Company updated successfully');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $company = Company::find($id)->delete();

        return redirect()->route('company.index')
            ->with('success', 'Company deleted successfully');
    }
}

resources/views/company/create.blade.php
@extends('layouts.app')

@section('template_title')
    Create Company
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Create Company</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('company.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('company.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/company/edit.blade.php
@extends('layouts.app')

@section('template_title')
    Update Company
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Update Company</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('company.update', $company->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('company.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/company/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">
        
        <div class="form-group">
            {{ Form::label('name') }}
            {{ Form::text('name', $company->name, ['class' => 'form-control' . ($errors->has('name') ? ' is-invalid' : ''), 'placeholder' => 'Name']) }}
            {!! $errors->first('name', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('email') }}
            {{ Form::text('email', $company->email, ['class' => 'form-control' . ($errors->has('email') ? ' is-invalid' : ''), 'placeholder' => 'Email']) }}
            {!! $errors->first('email', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
             {{ Form::label('logo_path') }}
             {{--
            {{ Form::text('logo_path', $company->logo_path, ['class' => 'form-control' . ($errors->has('logo_path') ? ' is-invalid' : ''), 'placeholder' => 'Logo Path']) }}
            {!! $errors->first('logo_path', '<div class="invalid-feedback">:message</div>') !!}
                         --}}

                         {{$company->logo_path??''}} <br>
                         {{$company->photo}}
            @if (!empty($company->photo))
                <img src="{{env('APP_URL')}}/storage/{{$company->photo}}" alt="">
            @endif
            
            @include('partials.filepond', ['formId'=>'logo'])
        </div>
        <div class="form-group">
            {{ Form::label('website') }}
            {{ Form::text('website', $company->website, ['class' => 'form-control' . ($errors->has('website') ? ' is-invalid' : ''), 'placeholder' => 'Website']) }}
            {!! $errors->first('website', '<div class="invalid-feedback">:message</div>') !!}
        </div>

    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>

resources/views/company/index.blade.php
@extends('layouts.app')

@section('template_title')
    Company
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div style="display: flex; justify-content: space-between; align-items: center;">

                            <span id="card_title">
                                {{ __('Company') }}
                            </span>

                             <div class="float-right">
                                <a href="{{ route('company.create') }}" class="btn btn-primary btn-sm float-right"  data-placement="left">
                                  {{ __('Create New') }}
                                </a>
                              </div>
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover">
                                <thead class="thead">
                                    <tr>
                                        <th>No</th>
                                        
										<th>Name</th>
										<th>Email</th>
										<th>Logo Path</th>
										<th>Website</th>

                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($companies as $company)
                                        <tr>
                                            <td>{{ ++$i }}</td>
                                            
											<td>{{ $company->name }}</td>
											<td>{{ $company->email }}</td>
											<td>{{ $company->logo_path }}</td>
											<td>{{ $company->website }}</td>

                                            <td>
                                                <form action="{{ route('company.destroy',$company->id) }}" method="POST">
                                                    <a class="btn btn-sm btn-primary " href="{{ route('company.show',$company->id) }}"><i class="fa fa-fw fa-eye"></i> Show</a>
                                                    <a class="btn btn-sm btn-success" href="{{ route('company.edit',$company->id) }}"><i class="fa fa-fw fa-edit"></i> Edit</a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i> Delete</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {!! $companies->links('vendor.pagination.bootstrap-4') !!}
            </div>
        </div>
    </div>
@endsection

resources/views/company/show.blade.php
@extends('layouts.app')

@section('template_title')
    {{ $company->name ?? 'Show Company' }}
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title">Show Company</span>
                        </div>
                        <div class="float-right">
                            <a class="btn btn-primary" href="{{ route('company.index') }}"> Back</a>
                        </div>
                    </div>

                    <div class="card-body">
                        
                        <div class="form-group">
                            <strong>Name:</strong>
                            {{ $company->name }}
                        </div>
                        <div class="form-group">
                            <strong>Email:</strong>
                            {{ $company->email }}
                        </div>
                        <div class="form-group">
                            <strong>Logo Path:</strong>
                            {{ $company->logo_path }}
                        </div>
                        <div class="form-group">
                            <strong>Website:</strong>
                            {{ $company->website }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection